# Generated by Django 3.1.2 on 2021-01-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmates_cards', '0002_auto_20210109_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassmateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='classmate_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classmates_cards.classmatedata'),
            preserve_default=False,
        ),
    ]
